services:
  journal:
    image: sukhov-journal:latest
    build: ./journal
    env_file:
      - journal/.env
    ports:
      - "8080:8080"
    depends_on:
      # - ai-voice
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=journal
      - POSTGRES_USER=journal
      - POSTGRES_PASSWORD=journal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ai-voice:
  #   build: ./ai-voice
  #   expose:
  #     - 8000

volumes:
  pgdata: